DateTime:
    type: custom-scalar
    config:
        serialize: ["App\\Common\\framework\\DateTimeGraphQLType", "serialize"]
        parseValue: ["App\\Common\\framework\\DateTimeGraphQLType", "parseValue"]
        parseLiteral: ["App\\Common\\framework\\DateTimeGraphQLType", "parseLiteral"]
