Query:
    type: object
    config:
        description: ''
        fields:
            allTodos:
                type: '[Todo]'
                resolve: "@=resolver('all_Todos', [args])"
            TodosByCompleted:
                type: '[Todo]'
                args:
                    completed:
                        type: 'Boolean'
                resolve: "@=resolver('Todo_by_completed', [args])"
